import { readdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const dir = join(process.cwd(), "src/components/ui");
const files = readdirSync(dir).filter(
  (f) => f.endsWith(".tsx") || f.endsWith(".ts"),
);

const lines = files.map((f) => {
  const name = basename(f, f.endsWith(".tsx") ? ".tsx" : ".ts");
  return `export * from "./components/ui/${name}";`;
});

const out = `// auto-generated by scripts/generate-index.ts\n${lines.join("\n")}\n`;
writeFileSync(join(process.cwd(), "src/index.ts"), out);

// biome-ignore lint/suspicious/noConsole: <Dev CLI only>
console.log(`Generated index.ts with ${files.length} component(s).`);
