import { readdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const dir = join(process.cwd(), "src/schema");
const files = readdirSync(dir).filter((f) => f.endsWith(".ts"));

const lines = files.map((f) => {
  const name = basename(f, f.endsWith(".schema.ts") ? ".schema.ts" : ".ts");
  return `export * from './schema/${name}';`;
});

const out = `// auto-generated by scripts/generate-index.ts\n${lines.join("\n")}\n`;
writeFileSync(join(process.cwd(), "src/index.ts"), out);

// biome-ignore lint/suspicious/noConsole: <Dev CLI only>
console.log(`Generated index.ts with ${files.length} schema(s).`);
